title: Ayush Singh
description: >
  I am a dedicated student with a strong interest in learning new technologies
  and improving my problem-solving skills. I enjoy working on programming and
  technical concepts and am continuously building my knowledge through practice,
  coursework, and small projects. I am eager to learn, grow, and gain real-world
  experience.
theme: jekyll-theme-minimal
