title: Ayush Singh
decription: description: "I am a dedicated student with a strong interest in learning new technologies and improving my problem-solving skills."
logo: /images/hs.jpg
theme: jekyll-theme-minimal
